### ISSUE TITLE
Idea: Don't throw exception when result comparison fails

### ISSUE THREAD

**Issue by hrj** [sn127/utils#15]
When comparing xml output in abandon tests for example, if the files don't match, it throws an exception similar to this:

```
[info]    Comparator: 
[info]       msg: test vectors are different
[info]   at fi.sn127.utils.testing.DirSuiteLike.$anonfun$testCaseExecutor$4(DirSuiteLike.scala:589)
[info]   at fi.sn127.utils.testing.DirSuiteLike.$anonfun$testCaseExecutor$4$adapted(DirSuiteLike.scala:568)
[info]   at scala.collection.immutable.List.foreach(List.scala:378)
[info]   at fi.sn127.utils.testing.DirSuiteLike.testCaseExecutor(DirSuiteLike.scala:568)
[info]   at fi.sn127.utils.testing.DirSuiteLike.testCaseExecutor$(DirSuiteLike.scala:519)
[info]   at co.uproot.abandon.DefaultArgsDirSuite.testCaseExecutor(DefaultArgsDirSuite.scala:10)
[info]   at fi.sn127.utils.testing.DirSuiteLike.$anonfun$registerDirSuiteTestCase$1(DirSuiteLike.scala:325)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
```

If you have a choice, it might be better to show a "diff" of the files.

**Comment by jaa127** [comment]
It would be nice, especially if the diff is small (only few lines). 

Second problem is that there is something wrong how DirSuite communicates errors to ScalaTest. It would be nice if the actual exception message could be more concise and trimmed (as with normal ScalaTest failures).
